shared:
  pipeline_batch_size: 20

data:
  chunk_size: 256
  chunk_overlap: 32
  file_extns:
    - "pdf"
    - "txt"

embedding:
  embedding_model: amazon.titan-embed-text-v2:0
  embedding_model_platform: bedrock
  embedding_model_platform_args:
    bedrock_aws_region: us-east-1
  normalize_embeddings: false
  hf_tokenizer_params: 
    truncation: true
    padding: true
  normalization_params: {'p': 2, 'dim': 1, 'eps': 1e-12}
  embedding_batch_size: 8

vector_db:
  db_type: faiss
  params: {gpu: False}
  similarity_threshold: 0.5
  similarity_fn: cosine
  use_existing_vector_db: true
  save_index: true
  num_gpus: 0
  vector_db_index_save_path: /media/automl/automlagent/vectorDB_index_save/semantic_segmentation/index.idx
  metadata_index_save_path: /media/automl/automlagent/vectorDB_metadata_save/semantic_segmentation/metadata.json
  vector_db_index_load_path: /media/automl/automlagent/vectorDB_index_save/semantic_segmentation/index.idx
  metadata_index_load_path: /media/automl/automlagent/vectorDB_metadata_save/semantic_segmentation/metadata.json

retriever:
  retriever_top_k: 10
  use_reranker: false
  reranker_top_k: 10
  reranker_model_name: BAAI/bge-large-en-v1.5
  reranker_model_platform: huggingface
  reranker_batch_size: 8
  num_gpus: 0
  reranker_model_platform_args:
    hf_tokenizer_params:
      padding: true
      truncation: true
      max_length: 4096
      return_tensors: pt

generator:
  generator_model_name: anthropic.claude-3-5-sonnet-20241022-v2:0
  generator_model_platform: bedrock
  generator_model_platform_args:
    bedrock_aws_region: us-west-2
    bedrock_generate_params:
      max_tokens: 8192
      anthropic_version: "bedrock-2023-05-31"
    hf_generate_params:
      max_new_tokens: 8192
  generator_query_prefix: You are a helpful coding assistant. You will be provided with a query and you must answer it to the best of your abilities. You will be provided with some additional context that is related to the query and will help you answer the question.
