
name: MCP Tests
on:
  push:
    paths:
      - 'src/autogluon/mcp/**'
      - 'tests/unittests/mcp/**'
      - '.github/workflows/mcp_tests.yml'
  pull_request:
    paths:
      - 'src/autogluon/mcp/**'
      - 'tests/unittests/mcp/**'

permissions:
  id-token: write
  contents: read

jobs:
  mcp_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: assistant_py3
          environment-file: .github/workflows_env/unittest_env.yml
          auto-update-conda: true
          python-version: "3.10"
          miniconda-version: "latest"
      
      - name: Run MCP Test
        uses: ./.github/actions/test-assistant
        with:
          aws-role-arn: ${{ secrets.AWS_CI_ROLE_ARN }}
          submodule-to-test: mcp
